# Site settings
title: Jeff Skelton
email: jeff@jeffskelton.net
phone_number: (323) 863 6107
description: > # this means to ignore newlines until "baseurl:"
 Software Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.jeffskelton.net" # the base hostname & protocol for your site
twitter_username: skeltron5000
github_username:  jeffskelton3
linkedin_username: jeffskelton

reading_time: false
words_per_minute: 200

# Owner/author information
owner:
  name: Jeff Skelton
  avatar: avatar.jpg
  bio: "Software developer, musician, burrito enthusiast."
  email: jeff@jeffskelton.net
  # Social networking links used in footer. Update and remove as you like.
  twitter: skeltron5000   
  facebook: 
  github: jeffskelton3        
  stackexchange: jeffskelton3
  linkedin: jeffskelton 

post_image_directory: /images/posts

# Amount of post to show on home page
paginate: 5

# Octopress settings
# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: hpstr/post
page_layout: hpstr/page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Build settings
markdown: kramdown
highlighter: rouge
exclude: 
  - ".vscode"
  - ".python-version"
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

