# Site settings
title: Jeff Skelton
email: jeff@jeffskelton.net
phone_number: (323) 316 8116
description: > # this means to ignore newlines until "baseurl:"
  Softare Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jeffskelton.net" # the base hostname & protocol for your site
twitter_username: skelton5000
github_username:  jeffskelton3
linkedin_username: jeffskelton

# Octopress settings
# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Build settings
markdown: kramdown
highlighter: rouge


